project:
  type: website
  output-dir: docs

website:
  title: "Bahman Sadeghi" 
  site-url: ''
  description: "This is Bahman Sadeghi's personal Blog."
  navbar:
    background: success
    right:
      - icon: house-heart
        href: 'https://github.com/bahmanapl' 
      - text: About Me
        href: about.qmd 
      - icon: github
        href: ''
      - icon: twitter
        href: ''
      - icon: youtube
        href: ''
          
format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

